#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : inputproto
Version  : 2.3.2
Release  : 10
URL      : http://xorg.freedesktop.org/releases/individual/proto/inputproto-2.3.2.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/proto/inputproto-2.3.2.tar.gz
Summary  : Input extension headers
Group    : Development/Tools
License  : MIT-Opengroup
Requires: inputproto-doc
BuildRequires : asciidoc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(xorg-macros)

%description
X Input Extension
This extension defines a protocol to provide additional input devices
management such as graphic tablets.

%package dev
Summary: dev components for the inputproto package.
Group: Development
Provides: inputproto-devel

%description dev
dev components for the inputproto package.


%package dev32
Summary: dev32 components for the inputproto package.
Group: Default

%description dev32
dev32 components for the inputproto package.


%package doc
Summary: doc components for the inputproto package.
Group: Documentation

%description doc
doc components for the inputproto package.


%prep
%setup -q -n inputproto-2.3.2
pushd ..
cp -a inputproto-2.3.2 build32
popd

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
%configure --disable-static  --libdir=/usr/lib32
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
pushd ../build32
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do mv $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/XI.h
/usr/include/X11/extensions/XI2.h
/usr/include/X11/extensions/XI2proto.h
/usr/include/X11/extensions/XIproto.h
/usr/lib64/pkgconfig/inputproto.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32inputproto.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/inputproto/*
