#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : inputproto
Version  : 2.3.1
Release  : 4
URL      : http://xorg.freedesktop.org/releases/individual/proto/inputproto-2.3.1.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/proto/inputproto-2.3.1.tar.gz
Summary  : Input extension headers
Group    : Development/Tools
License  : MIT-Opengroup
Requires: inputproto-doc
BuildRequires : asciidoc
BuildRequires : pkgconfig(xorg-macros)

%description
X Input Extension
This extension defines a protocol to provide additional input devices
management such as graphic tablets.

%package dev
Summary: dev components for the inputproto package.
Group: Development

%description dev
dev components for the inputproto package.


%package doc
Summary: doc components for the inputproto package.
Group: Documentation

%description doc
doc components for the inputproto package.


%prep
%setup -q -n inputproto-2.3.1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/XI.h
/usr/include/X11/extensions/XI2.h
/usr/include/X11/extensions/XI2proto.h
/usr/include/X11/extensions/XIproto.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/inputproto/*
